"""Canonical user-facing artifact format identifiers."""

NEXT_ACTION_FORMAT = "evidence-review/next-action"
REVIEW_PACKET_FORMAT = "evidence-review/review-packet"
WORKFLOW_STATE_FORMAT = "evidence-review/workflow-state"
CASE_MANIFEST_FORMAT = "evidence-review/case-manifest"
CONFIRMED_INPUT_SET_FORMAT = "evidence-review/confirmed-input-set"
DRAWING_QUALITY_FORMAT = "evidence-review/drawing-quality"
PAGE_IMAGE_FORMAT = "evidence-review/page-image"
SOURCE_INVENTORY_FORMAT = "evidence-review/source-inventory"
UNRESOLVED_LINKS_FORMAT = "evidence-review/unresolved-links"
CODEX_WORKSPACE_FORMAT = "evidence-review/codex-workspace"
WEB_RUNTIME_FORMAT = "evidence-review/chatgpt-web-runtime"
RELEASE_FORMAT = "evidence-review/release"
RELEASE_VALIDATION_FORMAT = "evidence-review/release-validation"
